CREATE TABLE subscriptions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscriber_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT current_timestamp,

    CONSTRAINT fk_subscriber_user FOREIGN KEY (subscriber_id) REFERENCES users(id),
    CONSTRAINT fk_target_user FOREIGN KEY (target_id) REFERENCES users(id),
    CONSTRAINT unique_subscription UNIQUE (subscriber_id, target_id)
);